import { useEffect, useState } from 'react';
import { supabase } from '../supabase';
import type { IconName } from '../../components/Icon';

/**
 * City Empire — the persistent per-player activity feed / notification
 * center. Real rows are pushed server-side at the exact moment a
 * rental/contract/mission/achievement/upgrade actually happens; flavor
 * rows (competitor news, event announcements) are lazily generated by
 * `ensure_activity_flavor()`. See
 * supabase/migrations/0037_city_activity.sql. Same security contract as
 * the rest of Empire: this file only ever reads the table directly.
 */

export type ActivityCategory = 'booking' | 'contract' | 'event' | 'finance' | 'competition' | 'mission';

export interface ActivityItem {
  id: string;
  category: ActivityCategory;
  icon: IconName;
  title: string;
  body: string | null;
  amount: number | null;
  cxPoints: number | null;
  isFlavor: boolean;
  createdAt: string;
}

interface ActivityRow {
  id: string;
  category: ActivityCategory;
  icon: IconName;
  title: string;
  body: string | null;
  amount: number | null;
  cx_points: number | null;
  is_flavor: boolean;
  created_at: string;
}

function mapActivity(row: ActivityRow): ActivityItem {
  return {
    id: row.id,
    category: row.category,
    icon: row.icon,
    title: row.title,
    body: row.body,
    amount: row.amount,
    cxPoints: row.cx_points,
    isFlavor: row.is_flavor,
    createdAt: row.created_at,
  };
}

/** Rolls flavor content (competitor news, event announcements), then
 *  reads the feed — same two-step shape as districts.ts's
 *  fetchDistrictDemand(). */
export async function fetchActivityFeed(userId: string, limit = 50): Promise<ActivityItem[]> {
  await supabase.rpc('ensure_activity_flavor');
  const { data, error } = await supabase
    .from('game_activity_feed')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);
  if (error) throw error;
  return (data as ActivityRow[]).map(mapActivity);
}

export function useActivityFeed(userId: string | undefined) {
  const [feed, setFeed] = useState<ActivityItem[] | null>(null);
  const [reload, setReload] = useState(0);
  useEffect(() => {
    if (!userId) {
      setFeed([]);
      return;
    }
    let cancelled = false;
    fetchActivityFeed(userId)
      .then((f) => !cancelled && setFeed(f))
      .catch(() => !cancelled && setFeed([]));
    return () => {
      cancelled = true;
    };
  }, [userId, reload]);
  return { feed, refresh: () => setReload((n) => n + 1) };
}
